$schema: "http://json-schema.org/draft-07/schema#"
$id: icon_border_progress
title: "`icon_border_progress`"
type: array
description: "Array of icon progress configurations. The progress border automatically matches the icon's border radius for visual consistency."
items:
  $ref: "#/definitions/icon_progress_config"

definitions:
  icon_progress_config:
    type: object
    properties:
      button:
        type: string
        description: "Button to apply progress to. Use 'main', 'main-button', or 'sub-button-N'"
      source:
        type: string
        description: "Source entity for progress value"
        format: "entity[attribute]"
      entity:
        type: string
        description: "[DEPRECATED] Use 'source' instead. Source entity for progress value"
        format: "entity[attribute]"
      start:
        oneOf:
          - type: number
          - type: string
        description: "Start value for progress range (default: 0)"
        default: 0
      end:
        oneOf:
          - type: number
          - type: string
        description: "End value for progress range (default: 100)"
        default: 100
      interpolate_colors:
        type: boolean
        description: "Whether to interpolate colors between stops"
        default: false
      color_stops:
        type: array
        description: "Array of color stops for progress visualization"
        items:
          $ref: "#/definitions/color_stop"
      background_color:
        type: string
        description: "Background color of the icon (supports DER)"
      backcolor:
        type: string
        description: "[DEPRECATED] Use 'background_color' instead"
      remaining_color:
        type: string
        description: "Color of the remaining progress section (supports DER)"
      remainingcolor:
        type: string
        description: "[DEPRECATED] Use 'remaining_color' instead"
      condition:
        oneOf:
          - $ref: "#/definitions/condition"
          - type: array
            items:
              $ref: "#/definitions/condition"
        description: "Conditions to show the progress border"
      effects:
        type: array
        description: "Array of visual effects to apply"
        items:
          type: object
      border_radius:
        oneOf:
          - type: number
            minimum: 0
          - type: string
        description: "Custom border radius for the progress border (overrides CSS border-radius). Can be a number (pixels) or CSS value (e.g., '10px', '50%')"
    required:
      - button
      - source

  color_stop:
    type: object
    properties:
      percent:
        type: number
        minimum: 0
        maximum: 100
        description: "Percentage value for this color stop"
      color:
        type: string
        description: "Color value (hex, rgb, named color, or DER entity)"
    required:
      - percent
      - color

  condition:
    oneOf:
      - type: object
        required: [condition, entity, state]
        properties:
          condition:
            const: state
          entity:
            type: string
          attribute:
            type: string
          state:
            oneOf:
              - type: string
              - type: number
              - type: array
                items:
                  oneOf:
                    - type: string
                    - type: number
      - type: object
        required: [condition, entity]
        properties:
          condition:
            const: numeric_state
          entity:
            type: string
          attribute:
            type: string
          above:
            oneOf:
              - type: number
              - type: string
          below:
            oneOf:
              - type: number
              - type: string
      - type: object
        required: [condition, entity]
        properties:
          condition:
            const: exists
          entity:
            type: string
          attribute:
            type: string
      - type: object
        required: [condition, conditions]
        properties:
          condition:
            const: and
          conditions:
            type: array
            items:
              $ref: "#/definitions/condition"
      - type: object
        required: [condition, conditions]
        properties:
          condition:
            const: or
          conditions:
            type: array
            items:
              $ref: "#/definitions/condition"
      - type: object
        required: [condition]
        properties:
          condition:
            const: not
          conditions:
            oneOf:
              - $ref: "#/definitions/condition"
              - type: array
                items:
                  $ref: "#/definitions/condition"
