$schema: "http://json-schema.org/draft-07/schema#"
$id: separator_as_timeline
title: "`separator_as_timeline`"
type: object
description: "Main config object"
$ref: "#/definitions/iconSettings"
properties:
  rounded_edges:
    type: boolean
    default: false
    description: Use rounded ends on each segment. Segments that pass through midnight will still be flat for optimal visuals.
  show_time_ticks:
    type: boolean
    default: false
    description: Show time ticks on the timeline
  show_current_time:
    type: boolean
    default: true
    description: Show the current time marker on the timeline.
  marker_color:
    type: string
    description: Color of the current time marker.
  highlight_active:
    type: boolean
    default: false
    description: Highlight segment icon when current time is within the segment period
  time_format:
    $ref: "#/definitions/timeFormat"
    type: object
    description: Global time formatting configuration.
    properties:
      timeline:
        $ref: "#/definitions/overridableTimeFormat"
        type: object
        description: Time formatting settings for the timeline. Overrides global formatting settings
      tooltip:
        $ref: "#/definitions/overridableTimeFormat"
        type: object
        description: Time formatting settings for the tooltip. Overrides global formatting settings
  ranges:
    description: List of time ranges to display on the timeline
    anyOf:
      - type: array
        title: Array of range
        items:
          $ref: "#/definitions/range"
      - type: object
        title: Dictionary of range with numbered keys
        additionalItems:
          $ref: "#/definitions/range"

definitions:
  iconSettings:
    type: object
    properties:
      icon_color:
        type: string
        description: Icon colour
      icon_background_color:
        type: string
        description: Icon background colour
      icon_outline_color:
        type: string
        description: Icon outline colour
      icon_active_color:
        type: string
        description: Icon active glow colour

  range:
    $ref: "#/definitions/iconSettings"
    type: object
    properties:
      start_entity:
        type: string
        description: >
          Entity whose state will be used as the start time (e.g. sensor.sun_next_dawn)
      start_attribute:
        type: string
        description: Attribute to use instead of state
      start:
        type: string
        description: Fixed start time (ignored if entity is set)
      end_entity:
        type: string
        description: Entity whose state will be used as the end time
      end_attribute:
        type: string
        description: Attribute to use instead of state
      end:
        type: string
        description: Fixed end time (ignored if entity is set)
      label:
        type: string
        description: Label to use for segment on tooltip
      color:
        type: string
        description: Color to use for this segment on the timeline
      source_entities:
        type: string
        description: Optional information to show in tooltip
  overridableTimeFormat:
    $ref: "#/definitions/timeFormat"
    type: object
    properties:
      override:
        type: boolean
        default: false
        description: Override global time formatting

  timeFormat:
    type: object
    properties:
      use_24_hour:
        type: boolean
        default: true
        description: Show time in 24-hour format
      append_suffix:
        type: boolean
        default: false
        description: Display AM/PM.
      pad_hours:
        type: boolean
        default: true
        description: "Zero-pad hours e.g. 5:00 becomes 05:00"
      show_minutes:
        type: boolean
        default: true
        description: Show minutes in times
