name: Build and Release Modules

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect_changes.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

      - name: Get last successful workflow commit
        id: last_success
        run: |
          LAST_SUCCESS=$(gh run list --workflow=release.yaml --branch=main --status=success --limit 1 --json headSha -q '.[0].headSha')
          echo "last_success=$LAST_SUCCESS" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect changed modules
        id: detect_changes
        run: |
          echo "Detecting changed modules since last successful workflow..."
          CHANGED=$(git diff --name-only ${{ steps.last_success.outputs.last_success }} ${{ github.sha }} \
            | grep '^modules/' \
            | grep -v '^modules/templates/' \
            | cut -d/ -f2 \
            | sort -u \
            | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "changed=$CHANGED" >> $GITHUB_OUTPUT

      - name: Build modules
        run: npm run build

  create-release:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: needs.build.outputs.changed != '[]'
    strategy:
      matrix:
        module: ${{ fromJson(needs.build.outputs.changed) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          MODULE=${{ matrix.module }}
          echo "Creating release for $MODULE..."

          cd modules/$MODULE

          # Parse ID and version
          ID=$(yq eval '.module_info.id' module.yaml)
          VERSION=$(yq eval '.module_info.version' module.yaml)
          NAME=$(yq eval '.module_info.name' module.yaml)
          TAG="$ID/v$VERSION"

          # Create a release
          gh release create "${ID}/v${VERSION}" \
            "dist/${ID}.yaml" \
            --title "${NAME} v${VERSION}" \
            --notes "Auto-generated build from module.yaml" \
            --target ${{ github.sha }}
